language: python

python:
  # - "2.6"
  - "2.7"
  # - "3.2"
  # - "3.3"

notifications:
    email: false

virtualenv:
    system_site_packages: true

before_install:
    - sudo apt-get install -qq python-numpy python-scipy

install:
    - pip install setuptools

script:
    # - python setup.py nosetests
    # - python tests.py
