sudo: false

language: python

python:
  - 2.7
  - 3.4

notifications:
  email: false

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
  - pip install coveralls simplejson ionize
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

install:
  - conda install --yes python=$TRAVIS_PYTHON_VERSION numpy scipy nose h5py coverage click matplotlib
  - python setup.py install

script:
  - coverage run --source=emigrate setup.py test
  - ls examples/

after_success:
  - coveralls
